# Generated by Django 5.0.6 on 2024-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Name',
            field=models.CharField(default='Nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='UMR',
            field=models.CharField(default='Nothing', max_length=7),
            preserve_default=False,
        ),
    ]
