# Generated by Django 5.0.6 on 2024-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_register_name_register_umr'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='design',
            field=models.CharField(default='UMR', max_length=15),
        ),
    ]
