# Generated by Django 5.0.6 on 2024-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fullname',
            new_name='branchaddress',
        ),
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AddField(
            model_name='register',
            name='hospitalname',
            field=models.CharField(default='Nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
